name = "PhysicsBox"
uuid = "e99edf11-c1e6-4411-aba0-b273fa09fd00"
authors = ["michaelSven <michael.sven.ferguson@gmail.com>"]
version = "0.1.0"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
